### ISSUE TITLE
What is the NBT branch?

### ISSUE THREAD

**Issue by Ezzocorbi** [solidDoWant/ProjectE-Custom-Conversions#4]
I can't find on Google what the NBT branch of ProjectE that you talk about is, can you tell me how do I get ProjectE to calculate Mekanism's EMC values after putting the Mekanism.json file in the custom conversions folder please? Thanks in advance!

**Comment by solidDoWant** [comment]
https://github.com/solidDoWant/ProjectE

You'll need to compile this and use it in place of your normal ProjectE. Currently only have a branch for 1.7.10.

**Comment by Ezzocorbi** [comment]
Thankyou very much!

**Comment by solidDoWant** [comment]
For anybody looking for the release binary, I've recompiled and uploaded it here: https://github.com/solidDoWant/ProjectE/releases/tag/1
