### ISSUE TITLE
I can't compile it.

### ISSUE THREAD

**Issue by Ezzocorbi** [solidDoWant/ProjectE-Custom-Conversions#5]
I don't know anything about mod developing so I searched online how to compile a mod from github and I tried but I keep getting this error:

C:\Users\******\Desktop\ProjectE-master>gradlew build
****************************
 Powered By MCP:
 http://modcoderpack.com/
 Searge, ProfMobius, Fesh0r,
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : unknown
****************************
:compileApiJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':apiCompile'.
> Could not resolve com.cricketcraft.chisel:Chisel2:2.3.10.100.
  Required by:
      java.moze_intel:ProjectE-master:1.7.10-PE1.9.4
   > Could not GET 'http://coloredlightscore.us.to/maven/chisel-2-dev/com/cricketcraft/chisel/Chisel2/2.3.10.100/Chisel2-2.3.10.100.pom'.
      > Connection to http://coloredlightscore.us.to refused

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 17.557 secs

C:\Users\******\Desktop\ProjectE-master>

Sorry to bother you again but can you please explain to me how I can compile this? Thanks in advance

**Comment by solidDoWant** [comment]
I'll be away from my computer and unavailable today, but I'll send you help on this tomorrow. In the mean time, please ensure you're using MCP 1.7.10. In short you'll have to find the correct versions of the dependencies (like Chisel 2.2.3.10.100) somewhere on the internet, deobfuscate them, and build against those libraries.

**Comment by Ezzocorbi** [comment]
Thanks for the reply! I actually don't even know how MCP works or what it is because I don't know anything about mod development. Soo how do I install it and how do I deobfuscate the mods? I'm a 100% noob on coding/making mods >.< (I understand if you can't/don't want to help, many people don't like dealing with noobs).

**Comment by solidDoWant** [comment]
No problem. I'm willing to help anybody who actually tries fix stuff themselves. I did some research, the issue above is due to #https://github.com/sinkillerj/ProjectE/issues/1131 ... which I apparently had at some point. I'm going to see if I can recompile the project using the fix listed in that link, and I'll update this repo with a fix as well as a release if I succeed.

**Comment by solidDoWant** [comment]
Try this jar (zipped. I _think_ I compiled everything right and this is the non-dev version, but I'm not sure.
[ProjectE-1.7.10-PE1.9.4.jar.zip](https://github.com/solidDoWant/ProjectE-Custom-Conversions/files/2152365/ProjectE-1.7.10-PE1.9.4.jar.zip)

Please let me know if it works so I can add it as a release for other people.

**Comment by Ezzocorbi** [comment]
Thankyou for compiling the mod, I tested it (I'm using forge 10.13.4.1614) and the game crashes before reaching the main menu. This is the console log that I got from MultiMC https://pastebin.com/Z2RqfcaT

**Comment by solidDoWant** [comment]
Looks like I forgot one step of the build process (it's been a few years). The mod should load now, but I don't know if the mod will work properly. Here's the new jar:


[ProjectE-1.7.10-PE1.9.4.jar.zip](https://github.com/solidDoWant/ProjectE-Custom-Conversions/files/2153004/ProjectE-1.7.10-PE1.9.4.jar.zip)

**Comment by Ezzocorbi** [comment]
Thankyou so much it works great! :D

**Comment by solidDoWant** [comment]
Great, thanks for attempting to fix the issue yourself first!
